const ERRORS = {
  ERR_LOGIN_FAIL: 'Your registed email address and password do not match. Please check and enter again.',
  ERR_USER_CREATED_FAIL: "We're sorry, but something went wrong. Please try again.",
  ERR_EMAIL_NOT_BLANK: 'Please enter your email address.',
  ERR_EMAIL_INVALID: 'Please enter your email address correctly.',
  ERR_PASSWORD_NOT_BLANK: 'Please enter your password.',
  ERR_EMAIL_ALREADY_TAKEN: 'Email is already taken.',
  ERR_PASSWORD_SIZE: 'Password must be at least 6 charaters long and no more than 20 characters long.',
  ERR_FIRSTNAME_NOT_BLANK: 'Please enter your first name.',
  ERR_FIRSTNAME_SIZE: 'First name must be no more than 50 characters long.',
  ERR_LASTNAME_NOT_BLANK: 'Please enter your last name.',
  ERR_LASTNAME_SIZE: 'Last name must be no more than 50 characters long',
  ERR_PASSWORD_NOT_MATCH: 'Passwords do not match.',
  ERR_TERMS_AND_CONDITION_NOT_CHECK: 'Please check to accept Terms and Conditions.',
  ERR_CATEGORY_PARENT_NOT_FOUND: 'Category parent {} is not found.',
  ERR_PARENT_ID_NOT_NULL: 'Parent Id must not be null.',
  ERR_CATEGORY_NOT_FOUND: 'Category {} is not found.',
  ERR_CATEGORY_DELETED_FAIL: 'Fail to delete category {}. Please try again.',
  ERR_CATEGORY_STILL_IN_PARENT:
    'There are some categories still owned by {}. Please delete all of them before delete {}.',
  ERR_PRODUCT_STILL_IN_CATEGORY:
    'There are some products still owned by {}. Please delete all of them before delete {}.',
  ERR_CATEGORY_PARENT_DELETED_FAIL: 'Fail to delete category parent {}. Please try again.',
  ERR_CATEGORY_PARENT_ALREADY_TAKEN: 'Category parent {} is already taken.',
  ERR_CATEGORY_ALREADY_TAKEN: 'Category {} is already taken.',
  ERR_PARENT_NAME_EXISTED: 'Parent name {} is already existed.',
  ERR_CATEGORY_NAME_EXISTED: 'Category name {} is already existed.',
  ERR_CATEGORY_PARENT_UPDATED_FAIL: 'Fail to update category parent {}. Please try again.',
  ERR_CATEGORY_UPDATED_FAIL: 'Fail to update category {}. Please try again.',
  ERR_CATEGORY_NAME_NOT_BLANK: 'Category name must not blank.',
  ERR_CATEGORY_NAME_SIZE: 'Category name must not be higher than 50 characters.',
  ERR_CATEGORY_PARENT_CREATED_FAIL: 'Fail to create category parent {}. Please try again.',
  ERR_CATEGORY_CREATED_FAIL: 'Fail to create category {}.',
  ERR_COLOR_NOT_FOUND: 'Color {} is not found.',
  ERR_COLOR_ALREADY_EXISTED: 'Color {} is already existed.',
  ERR_COLOR_NAME_ALREADY_TAKEN: 'Color name {} is already taken.',
  ERR_COLOR_SOURCE_ALREADY_TAKEN: 'Color source {} is already taken.',
  ERR_PRODUCT_STILL_HAVE_COLOR: 'There are some products still have this color.',
  ERR_COLOR_CREATED_FAIL: 'Fail to create color {}. Please try again.',
  ERR_COLOR_UPDATED_FAIL: 'Fail to update color {}. Please try again.',
  ERR_COLOR_DELETED_FAIL: 'Fail to delete color {}. Please try again.',
  ERR_COLOR_NAME_NOT_BLANK: 'Color name must not blank.',
  ERR_COLOR_NAME_SIZE: 'Color name must be lower than 50 characters.',
  ERR_COLOR_SOURCE_NOT_BLANK: 'Color source must not blank.',
  ERR_SIZE_NOT_FOUND: 'Size {} is not found.',
  ERR_IMAGE_URL_NOT_BLANK: 'Image url mot not blank.',
  ERR_PRODUCT_IMAGE_COLOR_MIN: 'Color code must be higher than 0.',
  ERR_SIZE_ID_NOT_NULL: 'Size Id must not null.',
  ERR_SIZE_NAME_SIZE: 'Size name must be lower than 10.',
  ERR_PRODUCT_ID_NOT_NULL: 'Product Id must not null.',
  ERR_PRODUCT_ID_MIN: 'Product Id must be higher than 1.',
  ERR_PRODUCT_CATEGORY_NOT_NULL: 'Product must belong to one category.',
  ERR_PRODUCT_CATEGORY_MIN: 'Category Id must be higher than 1.',
  ERR_PRODUCT_CATEGORY_NUMBER: 'Category Id must be number',
  ERR_PRODUCT_NAME_NOT_BLANK: 'Product name must not blank.',
  ERR_PRODUCT_NAME_SIZE: 'Product name must be higher than 1 and lower than 100 characters.',
  ERR_PRODUCT_PRICE_NOT_NULL: 'Price must not be null.',
  ERR_PRODUCT_PRICE_MIN: 'Price must be equal or greater than 1000.',
  ERR_PRODUCT_PRICE_NUMBER: 'Price must be number.',
  ERR_PRODUCT_SHORT_DESC_SIZE: 'Short description must lower than 1000 characters.',
  ERR_PRODUCT_MATERIAL_SIZE: 'Material must lower than 1000 characters.',
  ERR_PRODUCT_HANDLING_SIZE: 'Handling must lower than 1000 characters.',
  ERR_PRODUCT_SALE_NOT_NULL: 'Sale must not be null.',
  ERR_PRODUCT_PRICE_SALE_NOT_NULL: 'Price sale must not be null.',
  ERR_PRODUCT_PRICE_SALE_MIN: 'Price sale must be qual or greater than 1000.',
  ERR_PRODUCT_PRICE_SALE_NUMBER: 'Price sale must be number',
  ERR_PRODUCT_COLORS_NOT_EMPTY: 'Please provide color and its sizes for this product',
  ERR_PRODUCT_ADDED_TO_PARENT: 'Fail to add product to category parent, please try again with category child.',
  ERR_PRODUCT_NOT_FOUND: 'Product {} is not found.',
  ERR_PRODUCT_ALREADY_TAKEN: 'Product {} is already taken.',
  ERR_NOT_EXIST_TWO_SAME_COLORS: 'Cannot exist two same colors in the images list.',
  ERR_PRODUCT_LOADED_FAIL: 'Fail to load product {}. Please try again.',
  ERR_PRODUCT_CREATED_FAIL: 'Fail to create product {}. Please try again.',
  ERR_PRODUCT_UPDATED_FAIL: 'Fail to update product {}. Please try again.',
  ERR_PRODUCT_DELETED_FAIL: 'Fail to delete product {}. Please try again.',
  ERR_PRODUCT_IMAGES_REPLACED_FAIL: 'Fail to replace images of product {}. Please try again.',
  ERR_PRODUCT_REVIEW_ADDED_FAIL: 'Fail to add review to product {}, Please try again',
  ERR_REVIEW_PRODUCT_ID_NOT_NULL: 'Product Id must not null',
  ERR_REVIEW_USER_ID_NOT_NULL: 'User Id must not null',
  ERR_REVIEW_TITLE_NOT_BLANK: 'Vui lòng nhập tựa đề.',
  ERR_REVIEW_COMMENT_NOT_BLANK: 'Vui lòng nhập bình luận để đánh giá.',
  ERR_REVIEW_RATING_MIN: 'Rating must be higher than 1',
  ERR_REVIEW_RATING_NOT_NULL: 'Bạn phải đánh giá số sao cho sản phẩm để đăng đánh giá.',
  ERR_LOGIN_REQUIRED: 'Bạn cần đăng nhập để thực hiện hành động này.',
  ERR_DATA_CONVERT_FAIL: 'Sorry! We have problems about converting your data. Please try again.',
  ERR_BRAND_NOT_FOUND: 'Brand {} is not found.',
  ERR_BRAND_ID_NOT_NULL: 'Brand Id must not null.',
  ERR_BRAND_ID_NOT_NUMBER: 'Brand Id must be number',
  ERR_BRAND_ID_MIN: 'Brand Id must higher than 0.',
  ERR_SIZE_ALREADY_EXIST: 'Size {} is already existed in color {}.',
  ERR_COLOR_ALREADY_EXIST: 'Color {} is already existed.',
  ERR_SIZE_NOT_CHOOSE: 'Please choose a size to add.',
  ERR_COLOR_NOT_CHOOSE: 'Please choose a color to add.',
  ERR_CART_USER_ID_NOT_NULL: 'Please login to do this action.',
  ERR_CART_PRODUCT_ID_MIN: 'Product Id must be higher or equals to 1.',
  ERR_CART_COLOR_ID_NOT_NULL: 'Vui lòng chọn màu sản phẩm bạn muốn thêm vào giỏ hàng.',
  ERR_CART_COLOR_ID_MIN: 'Color Id must be higher or equals to 0.',
  ERR_CART_SIZE_ID_NOT_NULL: 'Vui lòng chọn kích thước sản phẩm bạn muốn thêm vào giỏ hàng.',
  ERR_CART_SIZE_ID_MIN: 'Size Id must be higer or equals to 1.',
  ERR_CART_AMOUNT_MIN: 'Please choose at least one item to add.',
  ERR_ADD_TO_CART_FAIL: 'Fail to add item to cart. Please try again.',
  ERR_REMOVE_ITEM_FAIL: 'Fail to remove item from cart. Please try again.',
  ERR_UPDATE_ITEM_QUANTITY_FAIL: 'Fail to update item quantity in cart. Please try again.',
  ERR_CLEAR_CART_FAIL: 'Fail to clear cart. Please try again.',
  ERR_CART_NOT_FOUND: 'Your cart is not found.',
  ERR_ITEM_CART_NOT_FOUND: 'This item is not found in your cart.',
  ERR_CURRENT_QUANTITY_LOWER: 'Not enough quantity to add to cart.',
  ERR_OUT_OF_STOCK: 'This item is out of stock.',
};

export default ERRORS;
