const SUCCESS = {
  USER_SIGNUP_SUCCESS: 'Congratulations, your account has been successfully created! Please login to use the service.',
  CATEGORY_PARENT_DELETED_SUCCESS: 'Delete category parent {} successful.',
  CATEGORY_DELETED_SUCCESS: 'Delete category {} successful.',
  CATEGORY_PARENT_UPDATED_SUCCESS: 'Update category parent {} successful.',
  CATEGORY_UPDATED_SUCCESS: 'Update category {} successful.',
  CATEGORY_PARENT_CREATED_SUCCESS: 'Create category parent {} successful.',
  CATEGORY_CREATED_SUCCESS: 'Create category {} successful.',
  COLOR_CREATED_SUCCESS: 'Create color {} successful.',
  COLOR_UPDATED_SUCCESS: 'Update color {} successful.',
  COLOR_DELETED_SUCCESS: 'Delete color {} successful.',
  PRODUCT_CREATED_SUCCESS: 'Create product {} successful.',
  PRODUCT_DELETED_SUCCESS: 'Delete product {} successful.',
  PRODUCT_UPDATED_SUCCESS: 'Update product {} successful.',
  PRODUCT_IMAGES_DELETED_SUCCESS: 'Remove images from product {} successful.',
  PRODUCT_IMAGES_UPDATED_SUCCESS: 'Update images to product {} successful.',
  PRODUCT_REVIEW_ADDED_SUCCESS: 'Post review to product successful.',
  SIZE_ADD_TO_COLOR_SUCCESS: 'Add size {} to color {} successful.',
  ADD_TO_CART_SUCCESS: 'Thêm sản phẩm vào giỏ thành công.',
  REMOVE_ITEM_SUCCESS: 'Remove item from cart successful.',
  UPDATE_ITEM_QUANTITY_SUCCESS: 'Update item quantity successful.',
  CLEAR_CART_SUCCESS: 'Clear cart successful.',
  LOAD_CART_SUCCESS: 'Load cart successful.',
};

export default SUCCESS;
